import Head from 'next/head'
import React from 'react'
import { Col, Container, Row } from 'styled-bootstrap-grid'
import { Games } from '../src/api/games'
import { Box } from '../src/components/UI/Box'

export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Главная страница</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <Row>
          <Col xs={12} md={6} lg={3}>
            <Box>Карточка</Box>
          </Col>
        </Row>
      </Container>
    </>
  )
}

export async function getStaticProps(context) {
  const { data } = await Games.getGamesList({})

  return {
    props: { data },
  }
}
